#ifndef DATAMATRIXGENERATORLIB_GLOBAL_H
#define DATAMATRIXGENERATORLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAMATRIXGENERATORLIB_LIBRARY)
#  define DATAMATRIXGENERATORLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAMATRIXGENERATORLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAMATRIXGENERATORLIB_GLOBAL_H
